import type { Metadata } from "next";
import {Libre_Baskerville, Lora, Sacramento} from "next/font/google";
import "@/styles/globals.scss";
import {NextFontWithVariable} from "next/dist/compiled/@next/font";

const libreBaskerville: NextFontWithVariable = Libre_Baskerville({
  weight: ["400", "500", "600", "700"],
  variable: "--font-libre",
  subsets: ["latin"],
});

const lora: NextFontWithVariable = Lora({
  weight: ["400", "500", "600", "700"],
  variable: "--font-lora",
  subsets: ["latin"],
});

const sacramento: NextFontWithVariable = Sacramento({
  weight: "400",
  variable: "--font-sacramento",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr" className={`${lora.variable} ${libreBaskerville.variable} `}>
      <body>{children}</body>
    </html>
  );
}
